language: c
script:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa-opam-experimental
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml-native-compilers opam
  - export OPAMYES=1
  - opam init
  - eval `opam config -env`
  - opam pin ppx_import .
  - opam install -y -d -t ppx_import
